version: '3.8'

services:
  miniserve:
    image: ghcr.io/tokenicrat/miniserve
    container_name: miniserve
    restart: unless-stopped
    environment:
      # Token for uploading & deleting
      # If unset, a random string would be generated; view it in stdout
      - AUTH_TOKEN=${AUTH_TOKEN}
      # Maximum upload size, in MB
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH}
      # Override `gunicorn.conf.py` with environmental variables
      # - GUNICORN_WORKERS=4
      # - GUNICORN_TIMEOUT=30
    volumes:
      - ./data:/data
    networks:
      - miniserve-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  # It's recommended to use your own NGINX instance
  nginx:
    image: nginx:alpine
    container_name: miniserve-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./data:/var/www/miniserve:ro
    networks:
      - miniserve-network

networks:
  miniserve-network:
